### PR TITLE
Refactored the code.

### PR DESCRIPTION
**Pull request by seanballais**
The code was rather inconsistent especially on the loops and if statements.

I am personal knack for readability so I changed your ?: operator to a regular if. I hope that wasn't bad.

### CODE REVIEW

**Comment by RodRitter** [comment]
Makes sense. Will still need to convert to min.js - I'll do that in the next commit

**Comment by seanballais** [comment]
Sure. What do you use to minify?

**Comment by RodRitter** [comment]
I use Grunt as my task runner. The default task is to minify.

**Comment by RodRitter** [comment]
I'm actually being really stupid. None of the functionality has changed so we shouldn't need to minify again. It only effected the main Kew.js file.

**Comment by seanballais** [comment]
Don't worry @RodRitter, we all do mistakes.

**Pull request merged**
